"""empty message

Revision ID: 93057c4af5fb
Revises: d7f075c52e75
Create Date: 2022-06-03 20:41:40.459347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93057c4af5fb'
down_revision = 'd7f075c52e75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('artist_id', sa.Integer(), nullable=False))
    op.add_column('Show', sa.Column('start_time', sa.DateTime(), nullable=False))
    op.create_foreign_key(None, 'Show', 'Artist', ['artist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.drop_column('Show', 'start_time')
    op.drop_column('Show', 'artist_id')
    # ### end Alembic commands ###
