"""empty message

Revision ID: 94a5695c6c31
Revises: b7b9df4e67c4
Create Date: 2022-06-04 00:06:35.479262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94a5695c6c31'
down_revision = 'b7b9df4e67c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('address', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
